### ISSUE TITLE
Attempt to read from field 'int android.view.View.mViewFlags' on a null object

### ISSUE THREAD

**Issue by Mahdiazadbar** [DevExchanges/AndroidCarouselLayout#3]
he guys. i use this lib. and i thinks that's is best. but in use it when i scroll i have error

```
 java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference
                                                                 at android.view.ViewGroup.canViewReceivePointerEvents(ViewGroup.java:2464)
                                                                 at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1726)
                                                                 at android.view.View.dispatchGenericMotionEvent(View.java:9375)
                                                                 at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2067)
                                                                 at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1769)
                                                                 at android.view.View.dispatchGenericMotionEvent(View.java:9375)
                                                                 at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2067)
                                                                 at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1769)
                                                                 at android.view.View.dispatchGenericMotionEvent(View.java:9375)
                                                                 at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2067)
                                                                 at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1769)
                                                                 at android.view.View.dispatchGenericMotionEvent(View.java:9375)
                                                                 at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2067)
                                                                 at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1769)
                                                                 at android.view.View.dispatchGenericMotionEvent(View.java:9375)
                                                                 at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2067)
                                                                 at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1769)
                                                                 at android.view.View.dispatchGenericMotionEvent(View.java:9375)
                                                                 at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2067)
                                                                 at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1769)
                                                                 at android.view.View.dispatchGenericMotionEvent(View.java:9375)
                                                                 at com.android.internal.policy.PhoneWindow$DecorView.superDispatchGenericMotionEvent(PhoneWindow.java:2411)
                                                                 at com.android.internal.policy.PhoneWindow.superDispatchGenericMotionEvent(PhoneWindow.java:1747)
                                                                 at android.app.Activity.dispatchGenericMotionEvent(Activity.java:2801)
                                                                 at android.support.v7.view.WindowCallbackWrapper.dispatchGenericMotionEvent(WindowCallbackWrapper.java:70)
                                                                 at com.android.internal.policy.PhoneWindow$DecorView.dispatchGenericMotionEvent(PhoneWindow.java:2378)
                                                                 at android.view.View.dispatchPointerEvent(View.java:9516)
                                                                 at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                 at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                 at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                 at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                 at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                                 at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
                                                                 at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
                                                                 at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                 at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                 at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit
```

please help me. thanks

**Comment by haemi** [comment]
did you solve this? Facing the same issue...

**Comment by bhupalreddykokkanti** [comment]
I am also facing same problem. Please help us if anybody solved this issue.

**Comment by bhupalreddykokkanti** [comment]
After getting lot of frustation I got one solution. Please make sure if you are running on emulator or real device. In emulator it is not working. Run on real device then It is working fine.

**Comment by matthewding** [comment]
Add this,and framework code dispatchhoverevent will not be carried out! I got this problem on Android M.  
public boolean dispatchHoverEvent(MotionEvent ev) {
		return true;
	}
